input:
  file: people.csv

spring:
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: true
      name: myJob
  flyway:
    enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/poc
    driver-class-name: org.postgresql.Driver
    username: admin
    password: 12345

logging:
  level:
    root: info
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"

